name: Fetch the latest BC Liquor Store Live Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1 15-24 * * *"
    - cron: "1 0-5 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Fetches repo
        uses: actions/checkout@v2
      - name: Installs python
        uses: actions/setup-python@v.2.2.2
        with:
          python-version: 3.9
      - name: Installs dependencies
        run: |-
          python -m pip install -r requirements.txt
      - name: Generate jsons
        run: |-
          python entrypoint.py
      - name: Add results to repo
        run: |-
          git config user.name "Automated run"
          git config user.email "actions@users.noreply.github.com"
          git add -A *.json
          timestamp=$(date -u -Is)
          git commit -m "Update data on ${timestamp}" || exit 0
          git push

